# Generated by Django 5.0.1 on 2024-03-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descrip', models.TextField()),
                ('imagen_investigacion', models.ImageField(upload_to='investigacion-imagenes/')),
                ('imagen_tif', models.ImageField(blank=True, upload_to='investigacion/')),
                ('pdf', models.FileField(blank=True, upload_to='investigacion/')),
                ('mejores_pdf', models.FileField(blank=True, upload_to='investigacion/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion.categoria')),
            ],
        ),
    ]
