# Generated by Django 5.0.1 on 2024-03-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_alter_investigacion_imagen_tif_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaI',
        ),
    ]
