# Generated by Django 5.0.1 on 2024-03-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0003_rename_categoria_categoriai'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='imagen_extra_1',
            field=models.ImageField(blank=True, upload_to='investigacion-imagenes-extras1/'),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='imagen_extra_2',
            field=models.ImageField(blank=True, upload_to='investigacion-imagenes-extras3/'),
        ),
    ]
