# Generated by Django 5.0.1 on 2024-03-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0004_investigacion_imagen_extra_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='imagen_extra_3',
            field=models.ImageField(blank=True, upload_to='investigacion-imagenes-extras3/'),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='imagen_extra_2',
            field=models.ImageField(blank=True, upload_to='investigacion-imagenes-extras2/'),
        ),
    ]
