# Generated by Django 5.0.1 on 2024-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0005_investigacion_imagen_extra_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
