# Generated by Django 5.0.1 on 2024-05-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0006_alter_investigacion_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('texto1', models.CharField(max_length=100)),
                ('texto2', models.CharField(max_length=100)),
                ('texto3', models.CharField(max_length=100)),
                ('imagen1', models.ImageField(upload_to='imagen-carrusel-1/')),
                ('imagen2', models.ImageField(upload_to='imagen-carrusel-2/')),
                ('imagen3', models.ImageField(upload_to='imagen-carrusel-3/')),
            ],
        ),
    ]
