# Generated by Django 5.0.1 on 2024-01-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'NoBinario'), ('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
    ]
