# Generated by Django 5.0.1 on 2024-01-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'noBinario'), ('H', 'hombre'), ('M', 'mujer')], max_length=1),
        ),
    ]
