# Generated by Django 5.0.1 on 2024-02-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_profileadditionalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
