# Generated by Django 5.0.1 on 2024-02-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileadditionalinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer'), ('noBinario', 'Prefiero no decirlo')], max_length=10),
        ),
    ]
