# Generated by Django 5.0.1 on 2024-02-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_alter_profileadditionalinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileadditionalinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
