# Generated by Django 5.0.1 on 2024-02-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_alter_profileadditionalinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileadditionalinfo',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
