# Generated by Django 5.0.1 on 2024-02-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_alter_profileadditionalinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaluserinfo',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
