# Generated by Django 5.0.4 on 2024-11-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Tipografias',
        ),
    ]
