# Generated by Django 5.0.4 on 2024-11-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_rename_userprofile_tipografias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipografias',
            name='font_family',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipografias',
            name='font_size',
            field=models.CharField(max_length=10),
        ),
    ]
