# Generated by Django 5.0.4 on 2024-11-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_alter_tipografias_font_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipografias',
            name='font_family',
        ),
        migrations.AddField(
            model_name='tipografias',
            name='fuente_texto',
            field=models.CharField(default='Arial', max_length=100),
        ),
        migrations.AddField(
            model_name='tipografias',
            name='fuente_titulo',
            field=models.CharField(default='Arial', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipografias',
            name='font_size',
            field=models.CharField(default='12', max_length=10),
        ),
    ]
