# Generated by Django 5.0.1 on 2024-03-06 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_categoria_nombre_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('video_enlace', models.URLField(blank=True)),
                ('video_archivo', models.FileField(blank=True, upload_to='videos/')),
                ('autor', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramienta', to='servicios.categoria')),
            ],
        ),
    ]
