# Generated by Django 5.0.1 on 2024-03-06 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_herramienta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='video_archivo',
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.categoria'),
        ),
    ]
