# Generated by Django 5.0.1 on 2024-03-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_servicio_delete_herramienta'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen_servicio',
            field=models.ImageField(blank=True, upload_to='servicios-imagenes/'),
        ),
    ]
