# Generated by Django 5.0.1 on 2024-03-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_servicio_imagen_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='autor_enlace',
            field=models.URLField(blank=True),
        ),
    ]
