# Generated by Django 5.0.1 on 2024-03-08 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_alter_servicio_autor_alter_servicio_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.categoria'),
        ),
    ]
