# Generated by Django 5.0.1 on 2024-03-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_alter_servicio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
