# Generated by Django 5.0.1 on 2024-03-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_alter_servicio_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='autor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
