# Generated by Django 5.0.1 on 2024-03-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_alter_servicio_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
