# Generated by Django 5.0.1 on 2024-03-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_servicio_descrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descrip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='licencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
