# Generated by Django 5.0.1 on 2024-03-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_remove_servicio_descripcion_alter_servicio_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='desarrollador',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
