# Generated by Django 5.0.1 on 2024-03-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0016_servicio_desarrollador'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='desarrollador_enlace',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_licencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_licencia_enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
