# Generated by Django 5.0.1 on 2024-03-11 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0017_servicio_desarrollador_enlace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='autor_enlace',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='licencia',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='licencia_enlace',
        ),
    ]
