# Generated by Django 5.0.1 on 2024-03-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0018_remove_servicio_autor_remove_servicio_autor_enlace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='desarrollador_enlace',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre_licencia_enlace',
            field=models.URLField(blank=True),
        ),
    ]
