# Generated by Django 5.0.1 on 2024-03-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0019_alter_servicio_desarrollador_enlace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='desarrollador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre_licencia',
            field=models.CharField(max_length=100),
        ),
    ]
