# Generated by Django 5.0.1 on 2024-05-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0021_alter_servicio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
