# Generated by Django 4.2.4 on 2024-01-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionprofesional',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
