# Generated by Django 5.0.1 on 2024-01-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_alter_informacionprofesional_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionprofesional',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='informacionprofesional',
            name='universidad',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
