# Generated by Django 5.0.1 on 2024-02-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0008_alter_informacionprofesional_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionprofesional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
