# Generated by Django 5.0.1 on 2024-02-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0010_alter_informacionprofesional_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoDeInteresInformacionProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesionales.informacionprofesional')),
            ],
        ),
    ]
