# Generated by Django 5.0.1 on 2024-02-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0011_campodeinteresinformacionprofesional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campodeinteresinformacionprofesional',
            name='campo',
        ),
        migrations.AddField(
            model_name='campodeinteresinformacionprofesional',
            name='campo0',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campodeinteresinformacionprofesional',
            name='campo1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campodeinteresinformacionprofesional',
            name='campo2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campodeinteresinformacionprofesional',
            name='campo3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campodeinteresinformacionprofesional',
            name='campo4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campodeinteresinformacionprofesional',
            name='campo5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campodeinteresinformacionprofesional',
            name='campo6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
