# Generated by Django 5.0.1 on 2024-02-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0012_remove_campodeinteresinformacionprofesional_campo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionprofesional',
            name='campo0',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='informacionprofesional',
            name='campo1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='informacionprofesional',
            name='campo2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='informacionprofesional',
            name='campo3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='informacionprofesional',
            name='campo4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='informacionprofesional',
            name='campo5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='informacionprofesional',
            name='campo6',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
