# Generated by Django 5.0.1 on 2024-02-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0013_informacionprofesional_campo0_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampoDeInteresInformacionProfesional',
        ),
    ]
