# Generated by Django 5.0.1 on 2024-02-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0014_delete_campodeinteresinformacionprofesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionprofesional',
            name='campus',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='informacionprofesional',
            name='facultad',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='informacionprofesional',
            name='grupo_investigacion',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
