# Generated by Django 5.0.1 on 2024-02-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0016_articulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='anio',
            field=models.CharField(max_length=4),
        ),
    ]
