# Generated by Django 5.0.1 on 2024-02-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0017_alter_articulos_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='enlace_articulo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='informacionprofesional',
            name='enlace_a_scholar',
            field=models.TextField(blank=True),
        ),
    ]
